### ISSUE TITLE
앞으로의 개선점 : 사진을 잘 남겨보자

### ISSUE THREAD

**Issue by youngkang-design** [tastelab/JM#1]
- 식탁보 구입 with @jiyoonjiyoon 
- 사진 잘 찍는 연구 필요
- 카메라 가져오기 @young-hwa

**Comment by wan2land** [comment]
ㅋㅋㅋㅋ issue도 사용해보는건가요.

**Comment by youngkang-design** [comment]
@wan2land 네 이것도 체크리스트 있으면 좋겠네여... 흠 하나씩 이슈를 남기면 좋으려나?
